### ISSUE TITLE
Post method and content in body

### ISSUE THREAD

**Issue by aulasau** [IvanProgramming/Telegraph_api#1]
Hi, man!
Have a problem with `create_page` method. I'm trying to create a page with huge text content. And it seems that your library is passing it as query string parameter. So I get  `414 Request-URI Too Large`. 
Telegra.ph supports passing parameters inside the request's body form. 

Can you fix this, please?

**Comment by IvanProgramming** [comment]
Hello! Thank you for participation.
Checked my code, it is really big issue, so I'll fix it ASAP
